defaults:
  - physicsnemo_default
  - arch: modified_fourier
  - scheduler: tf_exponential_lr
  - optimizer: adam
  - loss: sum
  - _self_

network_dir: "outputs_PNP"

training:
  rec_results_freq: 1000
  rec_constraint_freq: 1000
  max_steps: 2000000
  grad_agg_freq: 1
  ntk:
    use_ntk: false
    run_freq : 1000
    save_name : ntk # Set cuda_graphs: False if logging ntk value

scheduler:
  decay_rate: 0.95
  decay_steps: 2000

optimizer:
  lr: 5e-5

graph:
  func_arch: false

save_filetypes: "vtk,npz"

cuda_graphs: false
jit: false
